"""add_practice_deployment_note

Revision ID: 26d59dc1f528
Revises: cfdce740b759
Create Date: 2026-01-12 17:30:43.653062

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "26d59dc1f528"
down_revision = "cfdce740b759"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("practice", sa.Column("deployment_note", sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("practice", "deployment_note")
    # ### end Alembic commands ###
