"""drop temporary alias

Revision ID: 3289a8a04ba2
Revises: cd75eb275cb7
Create Date: 2026-01-04 17:06:57.446739

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "3289a8a04ba2"
down_revision = "cd75eb275cb7"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("technique", "temporary_alias")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("technique", sa.Column("temporary_alias", sa.String(length=120), nullable=True))
    # ### end Alembic commands ###
