"""remove_practice_deployment_note

Revision ID: f71a73e20503
Revises: 26d59dc1f528
Create Date: 2026-01-12 18:20:49.451309

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "f71a73e20503"
down_revision = "26d59dc1f528"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("practice", "deployment_note")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "practice",
        sa.Column("deployment_note", sa.String(length=120), autoincrement=False, nullable=True),
    )
    # ### end Alembic commands ###
