"""add temporary alias to technique

Revision ID: cfdce740b759
Revises: 3289a8a04ba2
Create Date: 2026-01-05 06:47:24.706739

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "cfdce740b759"
down_revision = "3289a8a04ba2"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("technique", sa.Column("temporary_alias", sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("technique", "temporary_alias")
    # ### end Alembic commands ###
