"""initial_schema

Revision ID: caf5fe8031cc
Revises:
Create Date: 2026-01-04 08:21:58.685830

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

from mnemosys_core.db.models import (
    BlockType,
    CompletionStatus,
    DomainType,
    FatigueProfile,
    QualityRating,
    SessionType,
)
from mnemosys_core.db.types import (
    DatabaseEnum,
    DatabaseEnumList,
    JSONEncodedDict,
    JSONEncodedList,
)

# revision identifiers, used by Alembic.
revision = 'caf5fe8031cc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    enum_types = (
        postgresql.ENUM(DomainType, name="DomainType"),
        postgresql.ENUM(FatigueProfile, name="FatigueProfile"),
        postgresql.ENUM(SessionType, name="SessionType"),
        postgresql.ENUM(BlockType, name="BlockType"),
        postgresql.ENUM(CompletionStatus, name="CompletionStatus"),
        postgresql.ENUM(QualityRating, name="QualityRating"),
    )
    bind = op.get_bind()
    for enum_type in enum_types:
        enum_type.create(bind, checkfirst=True)

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exercise',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('domains', DatabaseEnumList(DomainType), nullable=False),
    sa.Column('instrument_compatibility', JSONEncodedList(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_exercise')),
    sa.UniqueConstraint('name', name=op.f('uq_exercise_name'))
    )
    op.create_table('instrument',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('instrument_type', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_instrument')),
    sa.UniqueConstraint('name', name=op.f('uq_instrument_name'))
    )
    op.create_table('overload_dimension',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_overload_dimension')),
    sa.UniqueConstraint('name', name=op.f('uq_overload_dimension_name'))
    )
    op.create_table('technique',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_technique')),
    sa.UniqueConstraint('name', name=op.f('uq_technique_name'))
    )
    op.create_table('tuning',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('tuning_type', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tuning'))
    )
    op.create_table('exercise_overload_dimension_association',
    sa.Column('exercise_id', sa.Integer(), nullable=False),
    sa.Column('overload_dimension_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercise.id'], name=op.f('fk_exercise_overload_dimension_association_exercise_id_exercise')),
    sa.ForeignKeyConstraint(['overload_dimension_id'], ['overload_dimension.id'], name=op.f('fk_exercise_overload_dimension_association_overload_dimension_id_overload_dimension')),
    sa.PrimaryKeyConstraint('exercise_id', 'overload_dimension_id', name=op.f('pk_exercise_overload_dimension_association'))
    )
    op.create_table('exercise_state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exercise_id', sa.Integer(), nullable=False),
    sa.Column('last_practiced_date', sa.Date(), nullable=True),
    sa.Column('rolling_minutes_7d', sa.Integer(), nullable=False),
    sa.Column('rolling_minutes_28d', sa.Integer(), nullable=False),
    sa.Column('mastery_estimate', sa.Float(), nullable=False),
    sa.Column('last_fatigue_profile', DatabaseEnum(FatigueProfile), nullable=True),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercise.id'], name=op.f('fk_exercise_state_exercise_id_exercise')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_exercise_state')),
    sa.UniqueConstraint('exercise_id', name=op.f('uq_exercise_state_exercise_id'))
    )
    op.create_table('exercise_technique_association',
    sa.Column('exercise_id', sa.Integer(), nullable=False),
    sa.Column('technique_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercise.id'], name=op.f('fk_exercise_technique_association_exercise_id_exercise')),
    sa.ForeignKeyConstraint(['technique_id'], ['technique.id'], name=op.f('fk_exercise_technique_association_technique_id_technique')),
    sa.PrimaryKeyConstraint('exercise_id', 'technique_id', name=op.f('pk_exercise_technique_association'))
    )
    op.create_table('instrument_technique_association',
    sa.Column('instrument_id', sa.Integer(), nullable=False),
    sa.Column('technique_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['instrument_id'], ['instrument.id'], name=op.f('fk_instrument_technique_association_instrument_id_instrument')),
    sa.ForeignKeyConstraint(['technique_id'], ['technique.id'], name=op.f('fk_instrument_technique_association_technique_id_technique')),
    sa.PrimaryKeyConstraint('instrument_id', 'technique_id', name=op.f('pk_instrument_technique_association'))
    )
    op.create_table('keyboard_instrument',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['instrument.id'], name=op.f('fk_keyboard_instrument_id_instrument')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_keyboard_instrument'))
    )
    op.create_table('keyboard_instrument_tuning',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['tuning.id'], name=op.f('fk_keyboard_instrument_tuning_id_tuning')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_keyboard_instrument_tuning'))
    )
    op.create_table('percussion_instrument',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['instrument.id'], name=op.f('fk_percussion_instrument_id_instrument')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_percussion_instrument'))
    )
    op.create_table('percussion_instrument_tuning',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['tuning.id'], name=op.f('fk_percussion_instrument_tuning_id_tuning')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_percussion_instrument_tuning'))
    )
    op.create_table('practice',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('instrument_id', sa.Integer(), nullable=False),
    sa.Column('session_date', sa.Date(), nullable=False),
    sa.Column('session_type', DatabaseEnum(SessionType), nullable=False),
    sa.Column('total_minutes', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['instrument_id'], ['instrument.id'], name=op.f('fk_practice_instrument_id_instrument')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_practice'))
    )
    op.create_table('stringed_instrument',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('string_count', sa.Integer(), nullable=False),
    sa.Column('scale_length', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['instrument.id'], name=op.f('fk_stringed_instrument_id_instrument')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_stringed_instrument'))
    )
    op.create_table('stringed_instrument_tuning',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pitch_sequence', JSONEncodedList(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['tuning.id'], name=op.f('fk_stringed_instrument_tuning_id_tuning')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_stringed_instrument_tuning'))
    )
    op.create_table('wind_instrument',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['instrument.id'], name=op.f('fk_wind_instrument_id_instrument')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_wind_instrument'))
    )
    op.create_table('wind_instrument_tuning',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['tuning.id'], name=op.f('fk_wind_instrument_tuning_id_tuning')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_wind_instrument_tuning'))
    )
    op.create_table('exercise_instance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('practice_id', sa.Integer(), nullable=False),
    sa.Column('exercise_id', sa.Integer(), nullable=False),
    sa.Column('sequence_order', sa.Integer(), nullable=False),
    sa.Column('parameters', JSONEncodedDict(), nullable=False),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercise.id'], name=op.f('fk_exercise_instance_exercise_id_exercise')),
    sa.ForeignKeyConstraint(['practice_id'], ['practice.id'], name=op.f('fk_exercise_instance_practice_id_practice')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_exercise_instance'))
    )
    op.create_table('practice_block',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('practice_id', sa.Integer(), nullable=False),
    sa.Column('exercise_id', sa.Integer(), nullable=False),
    sa.Column('block_order', sa.Integer(), nullable=False),
    sa.Column('block_type', DatabaseEnum(BlockType), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercise.id'], name=op.f('fk_practice_block_exercise_id_exercise')),
    sa.ForeignKeyConstraint(['practice_id'], ['practice.id'], name=op.f('fk_practice_block_practice_id_practice')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_practice_block'))
    )
    op.create_table('stringed_instrument_tuning_association',
    sa.Column('stringed_instrument_id', sa.Integer(), nullable=False),
    sa.Column('stringed_instrument_tuning_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['stringed_instrument_id'], ['stringed_instrument.id'], name=op.f('fk_stringed_instrument_tuning_association_stringed_instrument_id_stringed_instrument')),
    sa.ForeignKeyConstraint(['stringed_instrument_tuning_id'], ['stringed_instrument_tuning.id'], name=op.f('fk_stringed_instrument_tuning_association_stringed_instrument_tuning_id_stringed_instrument_tuning')),
    sa.PrimaryKeyConstraint('stringed_instrument_id', 'stringed_instrument_tuning_id', name=op.f('pk_stringed_instrument_tuning_association'))
    )
    op.create_table('exercise_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exercise_instance_id', sa.Integer(), nullable=False),
    sa.Column('completion_status', DatabaseEnum(CompletionStatus), nullable=False),
    sa.Column('quality_rating', DatabaseEnum(QualityRating), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['exercise_instance_id'], ['exercise_instance.id'], name=op.f('fk_exercise_log_exercise_instance_id_exercise_instance')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_exercise_log')),
    sa.UniqueConstraint('exercise_instance_id', name=op.f('uq_exercise_log_exercise_instance_id'))
    )
    op.create_table('practice_block_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('practice_block_id', sa.Integer(), nullable=False),
    sa.Column('completed', DatabaseEnum(CompletionStatus), nullable=False),
    sa.Column('quality', DatabaseEnum(QualityRating), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['practice_block_id'], ['practice_block.id'], name=op.f('fk_practice_block_log_practice_block_id_practice_block')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_practice_block_log'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('practice_block_log')
    op.drop_table('exercise_log')
    op.drop_table('stringed_instrument_tuning_association')
    op.drop_table('practice_block')
    op.drop_table('exercise_instance')
    op.drop_table('wind_instrument_tuning')
    op.drop_table('wind_instrument')
    op.drop_table('stringed_instrument_tuning')
    op.drop_table('stringed_instrument')
    op.drop_table('practice')
    op.drop_table('percussion_instrument_tuning')
    op.drop_table('percussion_instrument')
    op.drop_table('keyboard_instrument_tuning')
    op.drop_table('keyboard_instrument')
    op.drop_table('instrument_technique_association')
    op.drop_table('exercise_technique_association')
    op.drop_table('exercise_state')
    op.drop_table('exercise_overload_dimension_association')
    op.drop_table('tuning')
    op.drop_table('technique')
    op.drop_table('overload_dimension')
    op.drop_table('instrument')
    op.drop_table('exercise')
    bind = op.get_bind()
    enum_types = (
        postgresql.ENUM(QualityRating, name="QualityRating"),
        postgresql.ENUM(CompletionStatus, name="CompletionStatus"),
        postgresql.ENUM(BlockType, name="BlockType"),
        postgresql.ENUM(SessionType, name="SessionType"),
        postgresql.ENUM(FatigueProfile, name="FatigueProfile"),
        postgresql.ENUM(DomainType, name="DomainType"),
    )
    for enum_type in enum_types:
        enum_type.drop(bind, checkfirst=True)

    # ### end Alembic commands ###
