"""add_temporary_alias_to_technique

Revision ID: cd75eb275cb7
Revises: b09360ef2753
Create Date: 2026-01-04 16:32:14.002506

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "cd75eb275cb7"
down_revision = "b09360ef2753"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("technique", sa.Column("temporary_alias", sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("technique", "temporary_alias")
    # ### end Alembic commands ###
