"""add_temporary_label_to_practice

Revision ID: b09360ef2753
Revises: caf5fe8031cc
Create Date: 2026-01-04 14:35:07.243021

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'b09360ef2753'
down_revision = 'caf5fe8031cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('practice', sa.Column('temporary_label', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('practice', 'temporary_label')
    # ### end Alembic commands ###
